import type { Career } from "./types";

/*
 * Curated catalog of 100+ careers. Static, versionable reference data consumed
 * by the Career Explorer, Compare, Skill Gap, and Simulator features. Salaries
 * are indicative annual USD ranges for illustration, not guarantees.
 */
export const CAREERS: Career[] = [
  // ── Technology & Software ────────────────────────────────────────────────
  { slug: "software-engineer", title: "Software Engineer", category: "Technology", tagline: "Design and build software systems.", whatDoes: "Designs, writes, tests, and maintains software applications and systems.", skills: ["Programming", "Data structures", "System design", "Testing", "Version control"], education: "Bachelor's in CS or equivalent experience", salary: { currency: "USD", min: 85000, max: 170000 }, demand: "Very High", growth: "+22% (much faster than average)", workLifeBalance: 4, difficulty: 3, companies: ["Google", "Microsoft", "Amazon", "Stripe"], certifications: ["AWS Certified Developer", "Oracle Java Certification"] },
  { slug: "frontend-developer", title: "Frontend Developer", category: "Technology", tagline: "Craft user-facing web experiences.", whatDoes: "Builds the visual, interactive parts of websites and web apps.", skills: ["HTML/CSS", "JavaScript", "React", "Accessibility", "UI implementation"], education: "Bachelor's or bootcamp / self-taught", salary: { currency: "USD", min: 70000, max: 150000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 2, companies: ["Meta", "Shopify", "Vercel", "Airbnb"], certifications: ["Meta Front-End Developer", "freeCodeCamp Certifications"] },
  { slug: "backend-developer", title: "Backend Developer", category: "Technology", tagline: "Power apps with servers and data.", whatDoes: "Builds server-side logic, APIs, and databases that power applications.", skills: ["APIs", "Databases", "Programming", "System design", "Security"], education: "Bachelor's in CS or equivalent", salary: { currency: "USD", min: 85000, max: 165000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Netflix", "Uber", "PayPal", "Atlassian"], certifications: ["AWS Certified Developer", "MongoDB Developer"] },
  { slug: "fullstack-developer", title: "Full-Stack Developer", category: "Technology", tagline: "Build end to end, front to back.", whatDoes: "Works across both frontend and backend to ship complete features.", skills: ["JavaScript", "React", "APIs", "Databases", "System design"], education: "Bachelor's or bootcamp", salary: { currency: "USD", min: 80000, max: 165000 }, demand: "Very High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Shopify", "Stripe", "GitLab", "Twilio"], certifications: ["Meta Full-Stack", "AWS Developer"] },
  { slug: "mobile-developer", title: "Mobile Developer", category: "Technology", tagline: "Build apps for phones and tablets.", whatDoes: "Develops native or cross-platform applications for iOS and Android.", skills: ["Swift/Kotlin", "React Native", "APIs", "UI implementation", "Testing"], education: "Bachelor's or bootcamp", salary: { currency: "USD", min: 80000, max: 160000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Apple", "Google", "Snap", "Spotify"], certifications: ["Google Associate Android Developer", "Apple Developer"] },
  { slug: "devops-engineer", title: "DevOps Engineer", category: "Technology", tagline: "Automate build, deploy, and run.", whatDoes: "Automates infrastructure, CI/CD, and keeps systems reliable at scale.", skills: ["Cloud / DevOps", "CI/CD", "Containers", "Scripting", "Monitoring"], education: "Bachelor's or equivalent experience", salary: { currency: "USD", min: 95000, max: 175000 }, demand: "Very High", growth: "Strong", workLifeBalance: 3, difficulty: 4, companies: ["Amazon", "HashiCorp", "Datadog", "Cloudflare"], certifications: ["AWS DevOps Engineer", "CKA (Kubernetes)"] },
  { slug: "cloud-architect", title: "Cloud Architect", category: "Technology", tagline: "Design cloud infrastructure at scale.", whatDoes: "Designs secure, scalable cloud architectures across providers.", skills: ["Cloud / DevOps", "System design", "Security", "Networking", "Cost optimization"], education: "Bachelor's + experience", salary: { currency: "USD", min: 120000, max: 210000 }, demand: "Very High", growth: "Strong", workLifeBalance: 3, difficulty: 4, companies: ["AWS", "Microsoft", "Google Cloud", "IBM"], certifications: ["AWS Solutions Architect Pro", "Google Professional Cloud Architect"] },
  { slug: "site-reliability-engineer", title: "Site Reliability Engineer", category: "Technology", tagline: "Keep large systems running.", whatDoes: "Blends software and operations to make systems reliable and observable.", skills: ["Cloud / DevOps", "Programming", "Monitoring", "Incident response", "System design"], education: "Bachelor's in CS or equivalent", salary: { currency: "USD", min: 110000, max: 200000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 4, companies: ["Google", "LinkedIn", "Netflix", "Dropbox"], certifications: ["CKA", "AWS DevOps Engineer"] },
  { slug: "security-engineer", title: "Security Engineer", category: "Technology", tagline: "Defend systems from attacks.", whatDoes: "Protects systems and data by finding and fixing security weaknesses.", skills: ["Cybersecurity", "Networking", "Programming", "Threat modeling", "Incident response"], education: "Bachelor's in CS/Security", salary: { currency: "USD", min: 100000, max: 190000 }, demand: "Very High", growth: "+33% (much faster)", workLifeBalance: 3, difficulty: 4, companies: ["CrowdStrike", "Palo Alto", "Cloudflare", "Okta"], certifications: ["CISSP", "OSCP"] },
  { slug: "qa-engineer", title: "QA Engineer", category: "Technology", tagline: "Ensure software quality.", whatDoes: "Designs tests and automation to catch bugs before users do.", skills: ["Testing", "Automation", "Programming", "Attention to detail", "APIs"], education: "Bachelor's or equivalent", salary: { currency: "USD", min: 65000, max: 130000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Microsoft", "SAP", "Oracle", "Salesforce"], certifications: ["ISTQB", "Selenium"] },
  { slug: "game-developer", title: "Game Developer", category: "Technology", tagline: "Build interactive games.", whatDoes: "Programs gameplay, graphics, and systems for video games.", skills: ["C++/C#", "Game engines", "Mathematics", "Graphics", "Optimization"], education: "Bachelor's in CS/Game Dev", salary: { currency: "USD", min: 70000, max: 150000 }, demand: "Growing", growth: "Moderate", workLifeBalance: 2, difficulty: 4, companies: ["Epic Games", "Riot", "Ubisoft", "EA"], certifications: ["Unity Certified", "Unreal Engine"] },
  { slug: "blockchain-developer", title: "Blockchain Developer", category: "Technology", tagline: "Build decentralized apps.", whatDoes: "Develops smart contracts and decentralized applications.", skills: ["Solidity", "Cryptography", "Programming", "Web development", "Security"], education: "Bachelor's or self-taught", salary: { currency: "USD", min: 100000, max: 190000 }, demand: "Growing", growth: "Volatile but strong", workLifeBalance: 3, difficulty: 4, companies: ["Coinbase", "ConsenSys", "Chainlink", "Polygon"], certifications: ["Certified Blockchain Developer", "Ethereum Developer"] },
  { slug: "embedded-engineer", title: "Embedded Systems Engineer", category: "Technology", tagline: "Program hardware devices.", whatDoes: "Writes low-level software that runs on hardware and IoT devices.", skills: ["C/C++", "Electronics", "RTOS", "Debugging", "Low-level programming"], education: "Bachelor's in EE/CS", salary: { currency: "USD", min: 85000, max: 160000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 4, companies: ["Tesla", "Intel", "Qualcomm", "Bosch"], certifications: ["Embedded C", "ARM Accredited Engineer"] },
  { slug: "database-administrator", title: "Database Administrator", category: "Technology", tagline: "Manage and tune databases.", whatDoes: "Keeps databases secure, performant, and reliable.", skills: ["Databases", "SQL", "Performance tuning", "Backup/recovery", "Security"], education: "Bachelor's in CS/IT", salary: { currency: "USD", min: 80000, max: 150000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Oracle", "IBM", "Snowflake", "MongoDB"], certifications: ["Oracle DBA", "Microsoft SQL Server"] },
  { slug: "systems-architect", title: "Systems Architect", category: "Technology", tagline: "Design large technical systems.", whatDoes: "Defines the high-level structure of complex software systems.", skills: ["System design", "Programming", "Cloud / DevOps", "Communication", "Trade-off analysis"], education: "Bachelor's + significant experience", salary: { currency: "USD", min: 130000, max: 220000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 5, companies: ["Amazon", "Microsoft", "Oracle", "SAP"], certifications: ["TOGAF", "AWS Solutions Architect Pro"] },

  // ── Data & AI ────────────────────────────────────────────────────────────
  { slug: "data-scientist", title: "Data Scientist", category: "Data & AI", tagline: "Turn data into decisions.", whatDoes: "Uses statistics and machine learning to extract insight from data.", skills: ["Machine learning / AI", "Statistics", "Python", "Data analysis", "Communication"], education: "Bachelor's/Master's in a quantitative field", salary: { currency: "USD", min: 95000, max: 180000 }, demand: "Very High", growth: "+35% (much faster)", workLifeBalance: 4, difficulty: 4, companies: ["Netflix", "Airbnb", "Meta", "Spotify"], certifications: ["Google Data Analytics", "TensorFlow Developer"] },
  { slug: "data-analyst", title: "Data Analyst", category: "Data & AI", tagline: "Find stories in the numbers.", whatDoes: "Analyzes data to answer business questions and build dashboards.", skills: ["Data analysis", "SQL", "Spreadsheets / Excel", "Visualization", "Communication"], education: "Bachelor's or certificate", salary: { currency: "USD", min: 60000, max: 110000 }, demand: "Very High", growth: "Strong", workLifeBalance: 4, difficulty: 2, companies: ["Deloitte", "Amazon", "Visa", "Nielsen"], certifications: ["Google Data Analytics", "Microsoft Power BI"] },
  { slug: "data-engineer", title: "Data Engineer", category: "Data & AI", tagline: "Build data pipelines.", whatDoes: "Designs and maintains the pipelines that move and prepare data.", skills: ["Databases", "Python", "Cloud / DevOps", "SQL", "Data modeling"], education: "Bachelor's in CS or equivalent", salary: { currency: "USD", min: 100000, max: 180000 }, demand: "Very High", growth: "Strong", workLifeBalance: 4, difficulty: 4, companies: ["Snowflake", "Databricks", "Uber", "LinkedIn"], certifications: ["Google Professional Data Engineer", "Databricks"] },
  { slug: "ml-engineer", title: "Machine Learning Engineer", category: "Data & AI", tagline: "Ship models to production.", whatDoes: "Builds and deploys machine learning systems at scale.", skills: ["Machine learning / AI", "Python", "System design", "Cloud / DevOps", "Mathematics"], education: "Bachelor's/Master's in CS", salary: { currency: "USD", min: 115000, max: 210000 }, demand: "Very High", growth: "+40% (much faster)", workLifeBalance: 3, difficulty: 5, companies: ["OpenAI", "Google DeepMind", "Meta", "Nvidia"], certifications: ["TensorFlow Developer", "AWS ML Specialty"] },
  { slug: "ai-engineer", title: "AI Engineer", category: "Data & AI", tagline: "Build AI-powered products.", whatDoes: "Integrates and builds applications on top of AI and LLM systems.", skills: ["Machine learning / AI", "Python", "APIs", "Prompt engineering", "System design"], education: "Bachelor's in CS or equivalent", salary: { currency: "USD", min: 120000, max: 220000 }, demand: "Very High", growth: "Explosive", workLifeBalance: 3, difficulty: 4, companies: ["OpenAI", "Anthropic", "Microsoft", "Cohere"], certifications: ["Azure AI Engineer", "TensorFlow Developer"] },
  { slug: "ai-researcher", title: "AI Researcher", category: "Data & AI", tagline: "Advance the frontier of AI.", whatDoes: "Researches novel machine learning methods and publishes findings.", skills: ["Machine learning / AI", "Mathematics", "Research", "Python", "Writing"], education: "PhD (typical)", salary: { currency: "USD", min: 140000, max: 300000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 5, companies: ["DeepMind", "OpenAI", "Anthropic", "FAIR"], certifications: ["—"] },
  { slug: "business-intelligence-analyst", title: "BI Analyst", category: "Data & AI", tagline: "Drive decisions with dashboards.", whatDoes: "Builds reports and dashboards that guide business strategy.", skills: ["Data analysis", "SQL", "Visualization", "Business acumen", "Communication"], education: "Bachelor's", salary: { currency: "USD", min: 70000, max: 125000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Tableau", "Power BI", "Looker", "Qlik"], certifications: ["Tableau Desktop", "Microsoft Power BI"] },
  { slug: "computer-vision-engineer", title: "Computer Vision Engineer", category: "Data & AI", tagline: "Teach machines to see.", whatDoes: "Builds systems that interpret images and video.", skills: ["Machine learning / AI", "Python", "Mathematics", "Deep learning", "OpenCV"], education: "Master's typical", salary: { currency: "USD", min: 115000, max: 210000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 5, companies: ["Tesla", "Nvidia", "Waymo", "Apple"], certifications: ["Deep Learning Specialization"] },
  { slug: "nlp-engineer", title: "NLP Engineer", category: "Data & AI", tagline: "Build language understanding.", whatDoes: "Develops systems that understand and generate human language.", skills: ["Machine learning / AI", "Python", "Linguistics", "Deep learning", "Mathematics"], education: "Master's typical", salary: { currency: "USD", min: 120000, max: 215000 }, demand: "Very High", growth: "Strong", workLifeBalance: 3, difficulty: 5, companies: ["OpenAI", "Anthropic", "Grammarly", "Hugging Face"], certifications: ["NLP Specialization"] },
  { slug: "quantitative-analyst", title: "Quantitative Analyst", category: "Data & AI", tagline: "Model markets with math.", whatDoes: "Builds mathematical models for trading and risk.", skills: ["Mathematics", "Statistics", "Programming", "Finance", "Data analysis"], education: "Master's/PhD in quantitative field", salary: { currency: "USD", min: 130000, max: 300000 }, demand: "High", growth: "Steady", workLifeBalance: 2, difficulty: 5, companies: ["Two Sigma", "Citadel", "Jane Street", "JPMorgan"], certifications: ["CFA", "CQF"] },
  { slug: "statistician", title: "Statistician", category: "Data & AI", tagline: "Design studies, model uncertainty.", whatDoes: "Applies statistical theory to collect and interpret data.", skills: ["Statistics", "Mathematics", "R/Python", "Research design", "Communication"], education: "Master's typical", salary: { currency: "USD", min: 80000, max: 140000 }, demand: "Growing", growth: "+30% (much faster)", workLifeBalance: 4, difficulty: 4, companies: ["CDC", "Pfizer", "Google", "Census Bureau"], certifications: ["SAS Certified Statistician"] },

  // ── Design & Creative ────────────────────────────────────────────────────
  { slug: "ux-designer", title: "UX Designer", category: "Design", tagline: "Design useful, usable products.", whatDoes: "Researches users and designs intuitive product experiences.", skills: ["UI / UX design", "User research", "Prototyping", "Empathy", "Communication"], education: "Bachelor's or certificate", salary: { currency: "USD", min: 75000, max: 145000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Figma", "Airbnb", "Adobe", "IBM"], certifications: ["Google UX Design", "NN/g UX"] },
  { slug: "ui-designer", title: "UI Designer", category: "Design", tagline: "Craft beautiful interfaces.", whatDoes: "Designs the visual look and feel of digital interfaces.", skills: ["UI / UX design", "Visual design", "Typography", "Prototyping", "Design systems"], education: "Bachelor's or certificate", salary: { currency: "USD", min: 70000, max: 135000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Figma", "Apple", "Spotify", "Canva"], certifications: ["Google UX Design", "Interaction Design Foundation"] },
  { slug: "product-designer", title: "Product Designer", category: "Design", tagline: "Own the whole design problem.", whatDoes: "Combines UX, UI, and product thinking to ship features.", skills: ["UI / UX design", "User research", "Prototyping", "Product thinking", "Communication"], education: "Bachelor's or portfolio", salary: { currency: "USD", min: 90000, max: 170000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Stripe", "Airbnb", "Linear", "Notion"], certifications: ["Google UX Design"] },
  { slug: "graphic-designer", title: "Graphic Designer", category: "Design", tagline: "Communicate through visuals.", whatDoes: "Creates visual content for brands, print, and digital.", skills: ["Graphic design", "Typography", "Adobe Creative Suite", "Branding", "Creativity"], education: "Bachelor's or portfolio", salary: { currency: "USD", min: 45000, max: 90000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 2, companies: ["Adobe", "Pentagram", "Canva", "Ad agencies"], certifications: ["Adobe Certified Professional"] },
  { slug: "motion-designer", title: "Motion Designer", category: "Design", tagline: "Bring designs to life.", whatDoes: "Creates animation and motion graphics for media and products.", skills: ["Animation", "After Effects", "Design", "Storytelling", "Creativity"], education: "Bachelor's or portfolio", salary: { currency: "USD", min: 55000, max: 110000 }, demand: "Growing", growth: "Moderate", workLifeBalance: 4, difficulty: 3, companies: ["Netflix", "Apple", "Buck", "Studios"], certifications: ["Adobe After Effects"] },
  { slug: "ux-researcher", title: "UX Researcher", category: "Design", tagline: "Understand users deeply.", whatDoes: "Plans and runs research to inform product decisions.", skills: ["User research", "Interviewing", "Data analysis", "Empathy", "Communication"], education: "Bachelor's/Master's (often HCI or psych)", salary: { currency: "USD", min: 85000, max: 160000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 3, companies: ["Google", "Meta", "Microsoft", "Spotify"], certifications: ["NN/g UX Research"] },
  { slug: "industrial-designer", title: "Industrial Designer", category: "Design", tagline: "Design physical products.", whatDoes: "Designs the form and function of manufactured products.", skills: ["Product design", "CAD", "Prototyping", "Materials", "Creativity"], education: "Bachelor's in Industrial Design", salary: { currency: "USD", min: 60000, max: 115000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 3, companies: ["Apple", "Dyson", "IDEO", "Tesla"], certifications: ["—"] },
  { slug: "interior-designer", title: "Interior Designer", category: "Design", tagline: "Shape spaces people love.", whatDoes: "Designs functional and aesthetic indoor spaces.", skills: ["Space planning", "CAD", "Creativity", "Client management", "Materials"], education: "Bachelor's in Interior Design", salary: { currency: "USD", min: 50000, max: 100000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 2, companies: ["Gensler", "AECOM", "Design firms", "Studios"], certifications: ["NCIDQ"] },
  { slug: "illustrator", title: "Illustrator", category: "Design", tagline: "Tell stories with drawings.", whatDoes: "Creates original artwork for publishing, brands, and media.", skills: ["Illustration", "Drawing", "Creativity", "Adobe", "Storytelling"], education: "Portfolio-driven", salary: { currency: "USD", min: 40000, max: 95000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 3, companies: ["Publishers", "Studios", "Agencies", "Freelance"], certifications: ["—"] },
  { slug: "animator", title: "Animator", category: "Design", tagline: "Create motion and character.", whatDoes: "Produces 2D/3D animation for film, games, and media.", skills: ["Animation", "3D software", "Storytelling", "Creativity", "Attention to detail"], education: "Bachelor's or portfolio", salary: { currency: "USD", min: 55000, max: 120000 }, demand: "Growing", growth: "Moderate", workLifeBalance: 3, difficulty: 4, companies: ["Pixar", "DreamWorks", "Disney", "ILM"], certifications: ["Autodesk Maya"] },

  // ── Product & Management ─────────────────────────────────────────────────
  { slug: "product-manager", title: "Product Manager", category: "Product & Management", tagline: "Decide what to build and why.", whatDoes: "Owns product strategy and coordinates teams to deliver value.", skills: ["Product thinking", "Communication", "Data analysis", "Leadership", "Prioritization"], education: "Bachelor's; MBA optional", salary: { currency: "USD", min: 100000, max: 200000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 4, companies: ["Google", "Stripe", "Atlassian", "Figma"], certifications: ["Pragmatic Institute", "Reforge"] },
  { slug: "project-manager", title: "Project Manager", category: "Product & Management", tagline: "Deliver projects on time.", whatDoes: "Plans, coordinates, and delivers projects within scope and budget.", skills: ["Project management tools", "Communication", "Planning", "Risk management", "Leadership"], education: "Bachelor's; PMP valued", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Deloitte", "IBM", "Accenture", "Construction/Tech"], certifications: ["PMP", "PRINCE2"] },
  { slug: "program-manager", title: "Program Manager", category: "Product & Management", tagline: "Coordinate many projects.", whatDoes: "Manages interdependent projects toward strategic goals.", skills: ["Program management", "Communication", "Stakeholder management", "Planning", "Leadership"], education: "Bachelor's + experience", salary: { currency: "USD", min: 100000, max: 180000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 4, companies: ["Microsoft", "Amazon", "Google", "Meta"], certifications: ["PgMP", "PMP"] },
  { slug: "scrum-master", title: "Scrum Master", category: "Product & Management", tagline: "Coach agile teams.", whatDoes: "Facilitates agile processes and removes blockers for the team.", skills: ["Agile", "Facilitation", "Communication", "Coaching", "Conflict resolution"], education: "Bachelor's; certification valued", salary: { currency: "USD", min: 85000, max: 145000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 2, companies: ["Spotify", "SAP", "ING", "Consultancies"], certifications: ["CSM", "PSM"] },
  { slug: "business-analyst", title: "Business Analyst", category: "Product & Management", tagline: "Bridge business and tech.", whatDoes: "Analyzes business needs and translates them into requirements.", skills: ["Requirements analysis", "Communication", "Data analysis", "Process mapping", "SQL"], education: "Bachelor's", salary: { currency: "USD", min: 70000, max: 125000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Deloitte", "Accenture", "Banks", "SaaS"], certifications: ["CBAP", "PMI-PBA"] },
  { slug: "operations-manager", title: "Operations Manager", category: "Product & Management", tagline: "Keep the business running.", whatDoes: "Oversees day-to-day operations and process efficiency.", skills: ["Operations", "Leadership", "Process improvement", "Data analysis", "Communication"], education: "Bachelor's; MBA optional", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "Steady", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["Amazon", "FedEx", "Manufacturing", "Retail"], certifications: ["Six Sigma", "PMP"] },
  { slug: "technical-program-manager", title: "Technical Program Manager", category: "Product & Management", tagline: "Ship complex technical programs.", whatDoes: "Drives cross-team technical initiatives to completion.", skills: ["Program management", "Technical fluency", "Communication", "Planning", "Leadership"], education: "Bachelor's in CS/Eng + experience", salary: { currency: "USD", min: 120000, max: 200000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 4, companies: ["Google", "Amazon", "Meta", "Microsoft"], certifications: ["PMP"] },

  // ── Business & Entrepreneurship ──────────────────────────────────────────
  { slug: "entrepreneur", title: "Entrepreneur", category: "Business", tagline: "Build something from nothing.", whatDoes: "Identifies opportunities and builds businesses to pursue them.", skills: ["Leadership", "Sales", "Resilience", "Strategy", "Communication"], education: "No formal requirement", salary: { currency: "USD", min: 0, max: 1000000 }, demand: "Growing", growth: "Uncapped, high-risk", workLifeBalance: 2, difficulty: 5, companies: ["Self / startups", "Y Combinator", "Techstars", "Angels"], certifications: ["—"] },
  { slug: "startup-founder", title: "Startup Founder", category: "Business", tagline: "Turn an idea into a company.", whatDoes: "Founds and leads a startup from concept to scale.", skills: ["Vision", "Fundraising", "Leadership", "Product thinking", "Sales"], education: "No formal requirement", salary: { currency: "USD", min: 0, max: 500000 }, demand: "Growing", growth: "Uncapped, high-risk", workLifeBalance: 1, difficulty: 5, companies: ["Y Combinator", "Sequoia", "a16z", "Self"], certifications: ["—"] },
  { slug: "management-consultant", title: "Management Consultant", category: "Business", tagline: "Solve tough business problems.", whatDoes: "Advises organizations on strategy, operations, and change.", skills: ["Problem solving", "Communication", "Data analysis", "Strategy", "Presentation"], education: "Bachelor's/MBA from strong school", salary: { currency: "USD", min: 90000, max: 200000 }, demand: "High", growth: "Steady", workLifeBalance: 2, difficulty: 4, companies: ["McKinsey", "BCG", "Bain", "Deloitte"], certifications: ["MBA"] },
  { slug: "business-development-manager", title: "Business Development Manager", category: "Business", tagline: "Grow revenue and partnerships.", whatDoes: "Finds and closes growth opportunities and partnerships.", skills: ["Sales", "Negotiation", "Communication", "Relationship building", "Strategy"], education: "Bachelor's", salary: { currency: "USD", min: 75000, max: 160000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["Salesforce", "Oracle", "SaaS", "Enterprises"], certifications: ["—"] },
  { slug: "venture-capitalist", title: "Venture Capitalist", category: "Business", tagline: "Invest in startups.", whatDoes: "Evaluates and funds early-stage companies for returns.", skills: ["Finance", "Judgment", "Networking", "Analysis", "Communication"], education: "Bachelor's/MBA + experience", salary: { currency: "USD", min: 150000, max: 500000 }, demand: "Stable", growth: "Competitive", workLifeBalance: 3, difficulty: 5, companies: ["Sequoia", "a16z", "Accel", "Benchmark"], certifications: ["MBA"] },
  { slug: "chief-executive", title: "Chief Executive (CEO)", category: "Business", tagline: "Lead the whole organization.", whatDoes: "Sets vision and is accountable for an organization's success.", skills: ["Leadership", "Strategy", "Communication", "Decision making", "Resilience"], education: "Varies; extensive experience", salary: { currency: "USD", min: 150000, max: 1000000 }, demand: "Stable", growth: "Top of ladder", workLifeBalance: 2, difficulty: 5, companies: ["Any company", "Startups", "Enterprises", "Nonprofits"], certifications: ["MBA (common)"] },
  { slug: "strategy-manager", title: "Strategy Manager", category: "Business", tagline: "Shape the company's direction.", whatDoes: "Develops and drives strategic initiatives across the business.", skills: ["Strategy", "Data analysis", "Communication", "Market research", "Leadership"], education: "Bachelor's/MBA", salary: { currency: "USD", min: 100000, max: 180000 }, demand: "Steady", growth: "Steady", workLifeBalance: 3, difficulty: 4, companies: ["Fortune 500", "Consultancies", "Tech", "Banks"], certifications: ["MBA"] },

  // ── Finance & Accounting ─────────────────────────────────────────────────
  { slug: "financial-analyst", title: "Financial Analyst", category: "Finance", tagline: "Guide money decisions.", whatDoes: "Analyzes financial data to guide investment and business decisions.", skills: ["Finance", "Spreadsheets / Excel", "Data analysis", "Modeling", "Communication"], education: "Bachelor's in Finance/Econ", salary: { currency: "USD", min: 65000, max: 120000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["JPMorgan", "Goldman Sachs", "Fidelity", "Corporates"], certifications: ["CFA", "FMVA"] },
  { slug: "investment-banker", title: "Investment Banker", category: "Finance", tagline: "Advise on big deals.", whatDoes: "Advises on mergers, acquisitions, and capital raising.", skills: ["Finance", "Modeling", "Negotiation", "Communication", "Stamina"], education: "Bachelor's/MBA from strong school", salary: { currency: "USD", min: 100000, max: 300000 }, demand: "High", growth: "Steady", workLifeBalance: 1, difficulty: 5, companies: ["Goldman Sachs", "Morgan Stanley", "JPMorgan", "Evercore"], certifications: ["CFA", "Series 79"] },
  { slug: "chartered-accountant", title: "Chartered Accountant", category: "Finance", tagline: "Master of accounts and audit.", whatDoes: "Provides accounting, audit, tax, and advisory services.", skills: ["Accounting", "Audit", "Taxation", "Attention to detail", "Ethics"], education: "CA qualification (ICAI/ACCA/CPA)", salary: { currency: "USD", min: 60000, max: 150000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 4, companies: ["Deloitte", "PwC", "EY", "KPMG"], certifications: ["CA", "ACCA / CPA"] },
  { slug: "actuary", title: "Actuary", category: "Finance", tagline: "Price risk with math.", whatDoes: "Uses statistics to assess financial risk for insurers and firms.", skills: ["Mathematics", "Statistics", "Finance", "Programming", "Communication"], education: "Bachelor's + actuarial exams", salary: { currency: "USD", min: 80000, max: 180000 }, demand: "Growing", growth: "+23% (much faster)", workLifeBalance: 4, difficulty: 5, companies: ["MetLife", "Prudential", "Aon", "Milliman"], certifications: ["SOA", "CAS"] },
  { slug: "financial-planner", title: "Financial Planner", category: "Finance", tagline: "Help people reach goals.", whatDoes: "Advises individuals on budgeting, investing, and retirement.", skills: ["Finance", "Communication", "Empathy", "Planning", "Sales"], education: "Bachelor's; CFP valued", salary: { currency: "USD", min: 60000, max: 130000 }, demand: "Growing", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Fidelity", "Vanguard", "Edward Jones", "Independent"], certifications: ["CFP"] },
  { slug: "accountant", title: "Accountant", category: "Finance", tagline: "Keep the books accurate.", whatDoes: "Prepares and reviews financial records and statements.", skills: ["Accounting", "Spreadsheets / Excel", "Attention to detail", "Taxation", "Ethics"], education: "Bachelor's in Accounting", salary: { currency: "USD", min: 50000, max: 95000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Deloitte", "PwC", "EY", "Corporates"], certifications: ["CPA"] },
  { slug: "auditor", title: "Auditor", category: "Finance", tagline: "Verify financial integrity.", whatDoes: "Examines financial records for accuracy and compliance.", skills: ["Audit", "Accounting", "Attention to detail", "Ethics", "Analysis"], education: "Bachelor's in Accounting", salary: { currency: "USD", min: 55000, max: 110000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["KPMG", "EY", "PwC", "Deloitte"], certifications: ["CPA", "CIA"] },
  { slug: "risk-manager", title: "Risk Manager", category: "Finance", tagline: "Protect the downside.", whatDoes: "Identifies and mitigates financial and operational risks.", skills: ["Risk analysis", "Finance", "Data analysis", "Communication", "Judgment"], education: "Bachelor's/Master's", salary: { currency: "USD", min: 90000, max: 170000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 4, companies: ["Banks", "Insurers", "Consultancies", "Corporates"], certifications: ["FRM", "PRM"] },
  { slug: "portfolio-manager", title: "Portfolio Manager", category: "Finance", tagline: "Manage investments.", whatDoes: "Makes investment decisions to grow a portfolio's value.", skills: ["Finance", "Analysis", "Judgment", "Risk management", "Communication"], education: "Bachelor's/MBA; CFA typical", salary: { currency: "USD", min: 120000, max: 300000 }, demand: "Stable", growth: "Competitive", workLifeBalance: 3, difficulty: 5, companies: ["BlackRock", "Fidelity", "Vanguard", "Hedge funds"], certifications: ["CFA"] },
  { slug: "tax-advisor", title: "Tax Advisor", category: "Finance", tagline: "Optimize tax outcomes.", whatDoes: "Advises clients on tax strategy and compliance.", skills: ["Taxation", "Accounting", "Attention to detail", "Communication", "Ethics"], education: "Bachelor's; CPA/EA valued", salary: { currency: "USD", min: 55000, max: 120000 }, demand: "Steady", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["Big Four", "H&R Block", "Boutiques", "Corporates"], certifications: ["CPA", "Enrolled Agent"] },

  // ── Marketing & Media ────────────────────────────────────────────────────
  { slug: "digital-marketer", title: "Digital Marketer", category: "Marketing & Media", tagline: "Grow brands online.", whatDoes: "Plans and runs campaigns across digital channels.", skills: ["Digital marketing", "Analytics", "Content writing", "SEO", "Creativity"], education: "Bachelor's or certificate", salary: { currency: "USD", min: 50000, max: 110000 }, demand: "High", growth: "Strong", workLifeBalance: 4, difficulty: 2, companies: ["HubSpot", "Google", "Agencies", "Startups"], certifications: ["Google Ads", "HubSpot"] },
  { slug: "content-strategist", title: "Content Strategist", category: "Marketing & Media", tagline: "Plan content that converts.", whatDoes: "Defines content strategy aligned to audience and goals.", skills: ["Content writing", "Strategy", "SEO", "Editing", "Analytics"], education: "Bachelor's", salary: { currency: "USD", min: 60000, max: 120000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["HubSpot", "Contentful", "Agencies", "Media"], certifications: ["HubSpot Content"] },
  { slug: "seo-specialist", title: "SEO Specialist", category: "Marketing & Media", tagline: "Win organic search.", whatDoes: "Optimizes sites and content to rank in search engines.", skills: ["SEO", "Analytics", "Content writing", "Technical SEO", "Research"], education: "Bachelor's or self-taught", salary: { currency: "USD", min: 50000, max: 105000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Ahrefs", "Semrush", "Agencies", "E-commerce"], certifications: ["Google Analytics", "Semrush"] },
  { slug: "social-media-manager", title: "Social Media Manager", category: "Marketing & Media", tagline: "Own the brand's voice.", whatDoes: "Grows and engages audiences across social platforms.", skills: ["Social media", "Content writing", "Creativity", "Analytics", "Community"], education: "Bachelor's or portfolio", salary: { currency: "USD", min: 45000, max: 95000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Brands", "Agencies", "Startups", "Media"], certifications: ["Hootsuite", "Meta Blueprint"] },
  { slug: "brand-manager", title: "Brand Manager", category: "Marketing & Media", tagline: "Steward the brand.", whatDoes: "Shapes brand positioning and marketing strategy.", skills: ["Branding", "Strategy", "Communication", "Analytics", "Creativity"], education: "Bachelor's; MBA optional", salary: { currency: "USD", min: 75000, max: 150000 }, demand: "Steady", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["P&G", "Unilever", "Nike", "Coca-Cola"], certifications: ["—"] },
  { slug: "copywriter", title: "Copywriter", category: "Marketing & Media", tagline: "Words that sell.", whatDoes: "Writes persuasive copy for ads, sites, and campaigns.", skills: ["Content writing", "Creativity", "Persuasion", "Editing", "Research"], education: "Portfolio-driven", salary: { currency: "USD", min: 45000, max: 100000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 2, companies: ["Agencies", "Brands", "Startups", "Freelance"], certifications: ["—"] },
  { slug: "growth-marketer", title: "Growth Marketer", category: "Marketing & Media", tagline: "Engineer growth loops.", whatDoes: "Runs experiments across the funnel to drive growth.", skills: ["Digital marketing", "Analytics", "Experimentation", "SQL", "Creativity"], education: "Bachelor's or self-taught", salary: { currency: "USD", min: 70000, max: 150000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 3, companies: ["Startups", "SaaS", "Consumer apps", "Agencies"], certifications: ["Reforge"] },
  { slug: "public-relations-specialist", title: "PR Specialist", category: "Marketing & Media", tagline: "Shape public perception.", whatDoes: "Manages communications and relationships with media.", skills: ["Communication", "Writing", "Relationship building", "Crisis management", "Strategy"], education: "Bachelor's in PR/Comms", salary: { currency: "USD", min: 50000, max: 105000 }, demand: "Steady", growth: "Steady", workLifeBalance: 3, difficulty: 2, companies: ["Agencies", "Corporates", "Nonprofits", "Government"], certifications: ["APR"] },
  { slug: "marketing-manager", title: "Marketing Manager", category: "Marketing & Media", tagline: "Lead marketing efforts.", whatDoes: "Plans and leads marketing strategy and teams.", skills: ["Marketing", "Leadership", "Analytics", "Communication", "Strategy"], education: "Bachelor's; MBA optional", salary: { currency: "USD", min: 80000, max: 160000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 3, companies: ["Brands", "Tech", "Agencies", "Retail"], certifications: ["—"] },
  { slug: "content-creator", title: "Content Creator", category: "Marketing & Media", tagline: "Build an audience.", whatDoes: "Creates video, audio, or written content for an audience.", skills: ["Content creation", "Editing", "Storytelling", "Creativity", "Consistency"], education: "No formal requirement", salary: { currency: "USD", min: 0, max: 500000 }, demand: "Growing", growth: "Uncapped, variable", workLifeBalance: 3, difficulty: 3, companies: ["YouTube", "TikTok", "Twitch", "Self"], certifications: ["—"] },

  // ── Healthcare & Medicine ────────────────────────────────────────────────
  { slug: "doctor", title: "Doctor (Physician)", category: "Healthcare", tagline: "Diagnose and treat patients.", whatDoes: "Diagnoses illness and provides medical care to patients.", skills: ["Medical knowledge", "Empathy", "Decision making", "Communication", "Stamina"], education: "Medical degree + residency", salary: { currency: "USD", min: 180000, max: 350000 }, demand: "Very High", growth: "+3% steady, essential", workLifeBalance: 2, difficulty: 5, companies: ["Hospitals", "Clinics", "Health systems", "Private practice"], certifications: ["Board Certification"] },
  { slug: "nurse", title: "Registered Nurse", category: "Healthcare", tagline: "Care at the front line.", whatDoes: "Provides and coordinates patient care in many settings.", skills: ["Patient care", "Empathy", "Clinical skills", "Communication", "Stamina"], education: "Nursing degree + licensure", salary: { currency: "USD", min: 65000, max: 120000 }, demand: "Very High", growth: "+6% (faster than average)", workLifeBalance: 3, difficulty: 3, companies: ["Hospitals", "Clinics", "Home health", "Schools"], certifications: ["RN License", "BLS/ACLS"] },
  { slug: "pharmacist", title: "Pharmacist", category: "Healthcare", tagline: "Medication experts.", whatDoes: "Dispenses medication and advises on safe use.", skills: ["Pharmacology", "Attention to detail", "Communication", "Ethics", "Chemistry"], education: "PharmD + licensure", salary: { currency: "USD", min: 100000, max: 150000 }, demand: "Stable", growth: "Steady", workLifeBalance: 4, difficulty: 4, companies: ["CVS", "Walgreens", "Hospitals", "Pharma"], certifications: ["PharmD License"] },
  { slug: "physiotherapist", title: "Physiotherapist", category: "Healthcare", tagline: "Restore movement.", whatDoes: "Helps patients recover movement and manage pain.", skills: ["Anatomy", "Patient care", "Empathy", "Manual therapy", "Communication"], education: "Degree in Physiotherapy + license", salary: { currency: "USD", min: 70000, max: 110000 }, demand: "Growing", growth: "+15% (much faster)", workLifeBalance: 4, difficulty: 3, companies: ["Clinics", "Hospitals", "Sports teams", "Rehab centers"], certifications: ["DPT License"] },
  { slug: "dentist", title: "Dentist", category: "Healthcare", tagline: "Care for oral health.", whatDoes: "Diagnoses and treats teeth and gum conditions.", skills: ["Dexterity", "Medical knowledge", "Empathy", "Attention to detail", "Communication"], education: "Dental degree + license", salary: { currency: "USD", min: 130000, max: 250000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 5, companies: ["Private practice", "Clinics", "Hospitals", "DSOs"], certifications: ["DDS/DMD License"] },
  { slug: "surgeon", title: "Surgeon", category: "Healthcare", tagline: "Operate to heal.", whatDoes: "Performs surgical procedures to treat conditions.", skills: ["Surgical skill", "Precision", "Decision making", "Stamina", "Leadership"], education: "Medical degree + surgical residency", salary: { currency: "USD", min: 250000, max: 500000 }, demand: "High", growth: "Steady", workLifeBalance: 1, difficulty: 5, companies: ["Hospitals", "Surgical centers", "Academic medicine"], certifications: ["Board Certification"] },
  { slug: "psychologist", title: "Psychologist", category: "Healthcare", tagline: "Support mental health.", whatDoes: "Assesses and treats mental and emotional health.", skills: ["Empathy", "Active listening", "Assessment", "Communication", "Research"], education: "Master's/Doctorate + license", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "Growing", growth: "+6% (faster)", workLifeBalance: 4, difficulty: 4, companies: ["Clinics", "Hospitals", "Schools", "Private practice"], certifications: ["Licensed Psychologist"] },
  { slug: "nutritionist", title: "Nutritionist / Dietitian", category: "Healthcare", tagline: "Guide healthy eating.", whatDoes: "Advises on diet and nutrition for health and performance.", skills: ["Nutrition science", "Empathy", "Communication", "Assessment", "Motivation"], education: "Bachelor's + credential", salary: { currency: "USD", min: 50000, max: 90000 }, demand: "Growing", growth: "+7% (faster)", workLifeBalance: 4, difficulty: 2, companies: ["Hospitals", "Clinics", "Sports", "Wellness"], certifications: ["RD / RDN"] },
  { slug: "medical-lab-technician", title: "Medical Lab Technician", category: "Healthcare", tagline: "Run the tests behind diagnoses.", whatDoes: "Performs lab tests that inform diagnosis and treatment.", skills: ["Lab technique", "Attention to detail", "Biology", "Safety", "Documentation"], education: "Associate/Bachelor's + certification", salary: { currency: "USD", min: 45000, max: 80000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 2, companies: ["Hospitals", "Labs", "Quest", "LabCorp"], certifications: ["ASCP"] },
  { slug: "radiologist", title: "Radiologist", category: "Healthcare", tagline: "Read the images.", whatDoes: "Interprets medical imaging to diagnose disease.", skills: ["Medical imaging", "Attention to detail", "Medical knowledge", "Decision making"], education: "Medical degree + radiology residency", salary: { currency: "USD", min: 300000, max: 500000 }, demand: "High", growth: "Steady", workLifeBalance: 3, difficulty: 5, companies: ["Hospitals", "Imaging centers", "Teleradiology"], certifications: ["Board Certification"] },
  { slug: "veterinarian", title: "Veterinarian", category: "Healthcare", tagline: "Care for animals.", whatDoes: "Diagnoses and treats illness in animals.", skills: ["Veterinary medicine", "Empathy", "Dexterity", "Communication", "Decision making"], education: "Veterinary degree + license", salary: { currency: "USD", min: 90000, max: 160000 }, demand: "Growing", growth: "+19% (much faster)", workLifeBalance: 3, difficulty: 5, companies: ["Clinics", "Animal hospitals", "Zoos", "Research"], certifications: ["DVM License"] },
  { slug: "healthcare-administrator", title: "Healthcare Administrator", category: "Healthcare", tagline: "Run health organizations.", whatDoes: "Manages operations of hospitals and health facilities.", skills: ["Management", "Operations", "Communication", "Finance", "Compliance"], education: "Bachelor's/Master's (MHA)", salary: { currency: "USD", min: 80000, max: 160000 }, demand: "Very High", growth: "+28% (much faster)", workLifeBalance: 3, difficulty: 3, companies: ["Hospitals", "Health systems", "Insurers", "Clinics"], certifications: ["FACHE"] },

  // ── Law & Public ─────────────────────────────────────────────────────────
  { slug: "lawyer", title: "Lawyer", category: "Law & Public", tagline: "Advise and advocate.", whatDoes: "Advises clients and represents them in legal matters.", skills: ["Legal research", "Writing", "Argumentation", "Attention to detail", "Ethics"], education: "Law degree + bar admission", salary: { currency: "USD", min: 80000, max: 200000 }, demand: "High", growth: "Steady", workLifeBalance: 2, difficulty: 5, companies: ["Law firms", "Corporates", "Government", "Nonprofits"], certifications: ["Bar Admission"] },
  { slug: "corporate-lawyer", title: "Corporate Lawyer", category: "Law & Public", tagline: "Law for business.", whatDoes: "Advises companies on contracts, deals, and compliance.", skills: ["Contract law", "Negotiation", "Writing", "Attention to detail", "Business acumen"], education: "Law degree + bar", salary: { currency: "USD", min: 120000, max: 300000 }, demand: "High", growth: "Steady", workLifeBalance: 2, difficulty: 5, companies: ["Big Law", "Corporates", "Investment banks"], certifications: ["Bar Admission"] },
  { slug: "paralegal", title: "Paralegal", category: "Law & Public", tagline: "Support legal work.", whatDoes: "Assists lawyers with research, documents, and cases.", skills: ["Legal research", "Writing", "Organization", "Attention to detail", "Software"], education: "Associate/Bachelor's or certificate", salary: { currency: "USD", min: 45000, max: 85000 }, demand: "High", growth: "+12% (faster)", workLifeBalance: 4, difficulty: 2, companies: ["Law firms", "Corporates", "Government", "Courts"], certifications: ["CP / ACP"] },
  { slug: "judge", title: "Judge", category: "Law & Public", tagline: "Interpret and apply the law.", whatDoes: "Presides over legal proceedings and rules on cases.", skills: ["Legal expertise", "Judgment", "Impartiality", "Writing", "Ethics"], education: "Law degree + years of practice", salary: { currency: "USD", min: 130000, max: 220000 }, demand: "Stable", growth: "Highly competitive", workLifeBalance: 3, difficulty: 5, companies: ["Courts", "Judiciary"], certifications: ["Bar + Appointment/Election"] },
  { slug: "policy-analyst", title: "Policy Analyst", category: "Law & Public", tagline: "Shape better policy.", whatDoes: "Researches issues and recommends policy solutions.", skills: ["Research", "Data analysis", "Writing", "Communication", "Critical thinking"], education: "Bachelor's/Master's", salary: { currency: "USD", min: 60000, max: 110000 }, demand: "Steady", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Government", "Think tanks", "Nonprofits", "NGOs"], certifications: ["—"] },
  { slug: "civil-services-officer", title: "Civil Services Officer", category: "Law & Public", tagline: "Serve the public.", whatDoes: "Administers government programs and public services.", skills: ["Administration", "Leadership", "Communication", "Ethics", "Analysis"], education: "Bachelor's + civil service exam", salary: { currency: "USD", min: 50000, max: 120000 }, demand: "Stable", growth: "Structured", workLifeBalance: 4, difficulty: 5, companies: ["Government", "Public sector", "Agencies"], certifications: ["Civil Services Exam"] },
  { slug: "human-rights-advocate", title: "Human Rights Advocate", category: "Law & Public", tagline: "Champion justice.", whatDoes: "Advocates for and protects human rights.", skills: ["Advocacy", "Research", "Communication", "Law", "Resilience"], education: "Bachelor's/Law degree", salary: { currency: "USD", min: 45000, max: 95000 }, demand: "Growing", growth: "Mission-driven", workLifeBalance: 3, difficulty: 4, companies: ["NGOs", "UN", "Nonprofits", "Legal aid"], certifications: ["—"] },

  // ── Engineering ──────────────────────────────────────────────────────────
  { slug: "mechanical-engineer", title: "Mechanical Engineer", category: "Engineering", tagline: "Design machines and systems.", whatDoes: "Designs, analyzes, and builds mechanical systems.", skills: ["CAD", "Physics", "Problem solving", "Materials", "Mathematics"], education: "Bachelor's in Mechanical Eng", salary: { currency: "USD", min: 70000, max: 130000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 4, companies: ["Tesla", "Boeing", "GE", "Ford"], certifications: ["PE License"] },
  { slug: "electrical-engineer", title: "Electrical Engineer", category: "Engineering", tagline: "Power the modern world.", whatDoes: "Designs electrical systems, circuits, and devices.", skills: ["Circuits", "Physics", "Mathematics", "CAD", "Problem solving"], education: "Bachelor's in Electrical Eng", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 4, companies: ["Intel", "Nvidia", "Siemens", "Tesla"], certifications: ["PE License"] },
  { slug: "civil-engineer", title: "Civil Engineer", category: "Engineering", tagline: "Build infrastructure.", whatDoes: "Designs and oversees roads, bridges, and buildings.", skills: ["Structural analysis", "CAD", "Project management", "Mathematics", "Materials"], education: "Bachelor's in Civil Eng", salary: { currency: "USD", min: 68000, max: 120000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 4, companies: ["AECOM", "Bechtel", "Jacobs", "Government"], certifications: ["PE License"] },
  { slug: "aerospace-engineer", title: "Aerospace Engineer", category: "Engineering", tagline: "Design aircraft and spacecraft.", whatDoes: "Develops aircraft, spacecraft, and propulsion systems.", skills: ["Aerodynamics", "Physics", "CAD", "Mathematics", "Simulation"], education: "Bachelor's/Master's in Aerospace", salary: { currency: "USD", min: 85000, max: 160000 }, demand: "Growing", growth: "Strong", workLifeBalance: 4, difficulty: 5, companies: ["NASA", "SpaceX", "Boeing", "Lockheed Martin"], certifications: ["PE License"] },
  { slug: "chemical-engineer", title: "Chemical Engineer", category: "Engineering", tagline: "Turn raw materials into products.", whatDoes: "Designs processes to convert materials into useful products.", skills: ["Chemistry", "Process design", "Mathematics", "Safety", "Problem solving"], education: "Bachelor's in Chemical Eng", salary: { currency: "USD", min: 80000, max: 150000 }, demand: "Steady", growth: "Steady", workLifeBalance: 4, difficulty: 5, companies: ["ExxonMobil", "Dow", "BASF", "Pfizer"], certifications: ["PE License"] },
  { slug: "biomedical-engineer", title: "Biomedical Engineer", category: "Engineering", tagline: "Engineer for health.", whatDoes: "Designs medical devices and healthcare technology.", skills: ["Biology", "Engineering", "CAD", "Problem solving", "Regulatory"], education: "Bachelor's/Master's in Biomedical Eng", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "Growing", growth: "+7% (faster)", workLifeBalance: 4, difficulty: 4, companies: ["Medtronic", "Stryker", "GE Healthcare", "Boston Scientific"], certifications: ["—"] },
  { slug: "environmental-engineer", title: "Environmental Engineer", category: "Engineering", tagline: "Engineer a cleaner planet.", whatDoes: "Designs solutions to environmental and sustainability problems.", skills: ["Environmental science", "Engineering", "Data analysis", "Regulatory", "Problem solving"], education: "Bachelor's in Environmental Eng", salary: { currency: "USD", min: 70000, max: 130000 }, demand: "Growing", growth: "Strong", workLifeBalance: 4, difficulty: 4, companies: ["AECOM", "Tetra Tech", "EPA", "Consultancies"], certifications: ["PE License"] },
  { slug: "robotics-engineer", title: "Robotics Engineer", category: "Engineering", tagline: "Build intelligent machines.", whatDoes: "Designs and programs robots and automation systems.", skills: ["Robotics", "Programming", "Control systems", "Mathematics", "Electronics"], education: "Bachelor's/Master's in Robotics/EE", salary: { currency: "USD", min: 90000, max: 170000 }, demand: "Growing", growth: "Strong", workLifeBalance: 4, difficulty: 5, companies: ["Boston Dynamics", "Tesla", "iRobot", "ABB"], certifications: ["—"] },
  { slug: "industrial-engineer", title: "Industrial Engineer", category: "Engineering", tagline: "Optimize systems and processes.", whatDoes: "Improves efficiency of production and operations.", skills: ["Process optimization", "Data analysis", "Statistics", "Problem solving", "Communication"], education: "Bachelor's in Industrial Eng", salary: { currency: "USD", min: 70000, max: 125000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Amazon", "Toyota", "Boeing", "Manufacturing"], certifications: ["Six Sigma"] },
  { slug: "automotive-engineer", title: "Automotive Engineer", category: "Engineering", tagline: "Design the future of mobility.", whatDoes: "Develops vehicles and automotive systems.", skills: ["Mechanical design", "CAD", "Physics", "Testing", "Problem solving"], education: "Bachelor's in Mechanical/Automotive Eng", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "Growing", growth: "EV-driven growth", workLifeBalance: 4, difficulty: 4, companies: ["Tesla", "Rivian", "Ford", "Toyota"], certifications: ["PE License"] },

  // ── Science & Research ───────────────────────────────────────────────────
  { slug: "research-scientist", title: "Research Scientist", category: "Science", tagline: "Push the boundaries of knowledge.", whatDoes: "Conducts original research to advance a scientific field.", skills: ["Research", "Statistics", "Writing", "Critical thinking", "Domain expertise"], education: "PhD (typical)", salary: { currency: "USD", min: 80000, max: 160000 }, demand: "Growing", growth: "Field-dependent", workLifeBalance: 4, difficulty: 5, companies: ["Universities", "National labs", "Pharma", "Tech R&D"], certifications: ["—"] },
  { slug: "biotechnologist", title: "Biotechnologist", category: "Science", tagline: "Engineer biology.", whatDoes: "Applies biology to develop products and processes.", skills: ["Molecular biology", "Lab technique", "Data analysis", "Research", "Chemistry"], education: "Bachelor's/Master's in Biotech", salary: { currency: "USD", min: 65000, max: 120000 }, demand: "Growing", growth: "Strong", workLifeBalance: 4, difficulty: 4, companies: ["Genentech", "Moderna", "Amgen", "Illumina"], certifications: ["—"] },
  { slug: "environmental-scientist", title: "Environmental Scientist", category: "Science", tagline: "Study and protect nature.", whatDoes: "Researches the environment and advises on protection.", skills: ["Environmental science", "Data analysis", "Field research", "Writing", "GIS"], education: "Bachelor's/Master's", salary: { currency: "USD", min: 60000, max: 110000 }, demand: "Growing", growth: "+6% (faster)", workLifeBalance: 4, difficulty: 3, companies: ["EPA", "Consultancies", "NGOs", "Research"], certifications: ["—"] },
  { slug: "physicist", title: "Physicist", category: "Science", tagline: "Understand how the universe works.", whatDoes: "Studies matter, energy, and the laws of nature.", skills: ["Mathematics", "Research", "Programming", "Critical thinking", "Modeling"], education: "PhD (typical)", salary: { currency: "USD", min: 85000, max: 160000 }, demand: "Stable", growth: "Competitive", workLifeBalance: 4, difficulty: 5, companies: ["Universities", "National labs", "CERN", "Tech R&D"], certifications: ["—"] },
  { slug: "chemist", title: "Chemist", category: "Science", tagline: "Explore matter and reactions.", whatDoes: "Studies substances and develops new materials and products.", skills: ["Chemistry", "Lab technique", "Analysis", "Safety", "Research"], education: "Bachelor's/PhD", salary: { currency: "USD", min: 60000, max: 120000 }, demand: "Steady", growth: "Steady", workLifeBalance: 4, difficulty: 4, companies: ["Pfizer", "Dow", "BASF", "Labs"], certifications: ["—"] },
  { slug: "geologist", title: "Geologist", category: "Science", tagline: "Read the story of the Earth.", whatDoes: "Studies the Earth's materials, processes, and history.", skills: ["Geology", "Field research", "Data analysis", "GIS", "Mapping"], education: "Bachelor's/Master's in Geology", salary: { currency: "USD", min: 60000, max: 120000 }, demand: "Steady", growth: "Resource-dependent", workLifeBalance: 4, difficulty: 3, companies: ["Energy", "Mining", "Government", "Consultancies"], certifications: ["PG License"] },

  // ── Education ────────────────────────────────────────────────────────────
  { slug: "teacher", title: "Teacher", category: "Education", tagline: "Shape the next generation.", whatDoes: "Educates students and fosters their growth.", skills: ["Communication", "Patience", "Subject expertise", "Empathy", "Organization"], education: "Bachelor's + teaching credential", salary: { currency: "USD", min: 45000, max: 85000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Schools", "Districts", "International schools"], certifications: ["Teaching License"] },
  { slug: "professor", title: "Professor", category: "Education", tagline: "Teach and research at university.", whatDoes: "Teaches and conducts research in higher education.", skills: ["Domain expertise", "Research", "Communication", "Writing", "Mentoring"], education: "PhD", salary: { currency: "USD", min: 70000, max: 180000 }, demand: "Stable", growth: "Competitive", workLifeBalance: 4, difficulty: 5, companies: ["Universities", "Colleges", "Research institutes"], certifications: ["—"] },
  { slug: "instructional-designer", title: "Instructional Designer", category: "Education", tagline: "Design how people learn.", whatDoes: "Creates effective learning experiences and courses.", skills: ["Learning design", "Writing", "Multimedia", "Empathy", "Assessment"], education: "Bachelor's/Master's", salary: { currency: "USD", min: 65000, max: 115000 }, demand: "Growing", growth: "Strong", workLifeBalance: 4, difficulty: 2, companies: ["EdTech", "Universities", "Corporates", "Coursera"], certifications: ["—"] },
  { slug: "education-consultant", title: "Education Consultant", category: "Education", tagline: "Advise on learning strategy.", whatDoes: "Advises schools and learners on education strategy.", skills: ["Education", "Communication", "Analysis", "Coaching", "Strategy"], education: "Bachelor's/Master's + experience", salary: { currency: "USD", min: 55000, max: 110000 }, demand: "Steady", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Consultancies", "Schools", "EdTech", "Independent"], certifications: ["—"] },

  // ── Aviation & Transport ─────────────────────────────────────────────────
  { slug: "pilot", title: "Airline Pilot", category: "Aviation & Transport", tagline: "Fly people and cargo safely.", whatDoes: "Operates aircraft to transport passengers and goods.", skills: ["Flying", "Decision making", "Situational awareness", "Communication", "Discipline"], education: "Flight training + licenses/ratings", salary: { currency: "USD", min: 90000, max: 300000 }, demand: "High", growth: "+4%, pilot shortage", workLifeBalance: 3, difficulty: 5, companies: ["Delta", "United", "Emirates", "Cargo carriers"], certifications: ["ATP License", "Type Ratings"] },
  { slug: "air-traffic-controller", title: "Air Traffic Controller", category: "Aviation & Transport", tagline: "Keep the skies orderly.", whatDoes: "Coordinates aircraft movement safely and efficiently.", skills: ["Situational awareness", "Decision making", "Communication", "Focus", "Calm under pressure"], education: "FAA/authority training", salary: { currency: "USD", min: 90000, max: 180000 }, demand: "Stable", growth: "Steady", workLifeBalance: 3, difficulty: 5, companies: ["FAA", "Air navigation authorities"], certifications: ["ATC Certification"] },
  { slug: "logistics-manager", title: "Logistics Manager", category: "Aviation & Transport", tagline: "Move goods efficiently.", whatDoes: "Plans and manages the flow of goods and supply chains.", skills: ["Supply chain", "Operations", "Data analysis", "Communication", "Problem solving"], education: "Bachelor's", salary: { currency: "USD", min: 65000, max: 130000 }, demand: "High", growth: "Strong", workLifeBalance: 3, difficulty: 3, companies: ["Amazon", "FedEx", "DHL", "Maersk"], certifications: ["APICS CSCP"] },

  // ── Architecture, Media & Other ──────────────────────────────────────────
  { slug: "architect", title: "Architect", category: "Architecture & Built", tagline: "Design the spaces we live in.", whatDoes: "Designs buildings that are safe, functional, and beautiful.", skills: ["Design", "CAD", "Building codes", "Creativity", "Project management"], education: "Professional degree + licensure", salary: { currency: "USD", min: 65000, max: 130000 }, demand: "Steady", growth: "Steady", workLifeBalance: 3, difficulty: 4, companies: ["Gensler", "Foster + Partners", "AECOM", "Studios"], certifications: ["Architect License (ARE)"] },
  { slug: "journalist", title: "Journalist", category: "Marketing & Media", tagline: "Inform the public.", whatDoes: "Researches and reports news stories across media.", skills: ["Writing", "Research", "Interviewing", "Ethics", "Communication"], education: "Bachelor's in Journalism/related", salary: { currency: "USD", min: 40000, max: 90000 }, demand: "Stable", growth: "Evolving", workLifeBalance: 3, difficulty: 3, companies: ["News outlets", "Magazines", "Broadcast", "Digital media"], certifications: ["—"] },
  { slug: "photographer", title: "Photographer", category: "Design", tagline: "Capture moments and stories.", whatDoes: "Creates photographs for clients, media, or art.", skills: ["Photography", "Composition", "Editing", "Creativity", "Client management"], education: "Portfolio-driven", salary: { currency: "USD", min: 35000, max: 90000 }, demand: "Steady", growth: "Moderate", workLifeBalance: 4, difficulty: 2, companies: ["Studios", "Media", "Agencies", "Freelance"], certifications: ["—"] },
  { slug: "chef", title: "Chef", category: "Hospitality", tagline: "Create memorable food.", whatDoes: "Designs menus and leads kitchens to prepare food.", skills: ["Culinary skill", "Creativity", "Leadership", "Stamina", "Time management"], education: "Culinary school or apprenticeship", salary: { currency: "USD", min: 45000, max: 100000 }, demand: "High", growth: "Steady", workLifeBalance: 2, difficulty: 4, companies: ["Restaurants", "Hotels", "Resorts", "Own venture"], certifications: ["Culinary Certification"] },
  { slug: "cybersecurity-analyst", title: "Cybersecurity Analyst", category: "Technology", tagline: "Monitor and defend.", whatDoes: "Monitors systems and responds to security threats.", skills: ["Cybersecurity", "Networking", "Threat analysis", "Incident response", "Scripting"], education: "Bachelor's or certifications", salary: { currency: "USD", min: 75000, max: 140000 }, demand: "Very High", growth: "+32% (much faster)", workLifeBalance: 3, difficulty: 3, companies: ["CrowdStrike", "Mandiant", "Banks", "MSSPs"], certifications: ["Security+", "CEH"] },
  { slug: "hr-manager", title: "HR Manager", category: "Business", tagline: "Grow people and culture.", whatDoes: "Leads hiring, development, and workplace culture.", skills: ["Communication", "Empathy", "Conflict resolution", "Organization", "Judgment"], education: "Bachelor's in HR/related", salary: { currency: "USD", min: 70000, max: 140000 }, demand: "High", growth: "Steady", workLifeBalance: 4, difficulty: 3, companies: ["Enterprises", "Startups", "Consultancies", "Any sector"], certifications: ["SHRM-CP", "PHR"] },
];

const BY_SLUG: Record<string, Career> = CAREERS.reduce<Record<string, Career>>((acc, c) => {
  acc[c.slug] = c;
  return acc;
}, {});

export function getCareer(slug: string): Career | null {
  return BY_SLUG[slug] ?? null;
}

export function getCareers(): Career[] {
  return CAREERS;
}

export const CAREER_CATEGORIES: string[] = Array.from(new Set(CAREERS.map((c) => c.category))).sort();

export const CAREER_COUNT = CAREERS.length;
