import type { LearningResource } from "./types";

/*
 * Curated catalog of high-quality, widely-recognized learning resources.
 * Static and versionable — no external fetch. `skills` tags align with the
 * assessment's skill labels so the hub can personalize recommendations.
 */
export const LEARNING_CATALOG: LearningResource[] = [
  // ── Programming & CS foundations ─────────────────────────────────────────
  {
    id: "cs50",
    title: "CS50: Introduction to Computer Science",
    provider: "Harvard / edX",
    url: "https://cs50.harvard.edu/x/",
    description: "The classic, rigorous introduction to programming and computer science.",
    category: "Programming",
    type: "course",
    level: "beginner",
    cost: "free",
    skills: ["Programming"],
  },
  {
    id: "freecodecamp",
    title: "freeCodeCamp Curriculum",
    provider: "freeCodeCamp",
    url: "https://www.freecodecamp.org/learn",
    description: "Thousands of hours of hands-on coding across web, data, and more — free forever.",
    category: "Web Development",
    type: "practice",
    level: "beginner",
    cost: "free",
    skills: ["Programming", "Web development"],
  },
  {
    id: "theodinproject",
    title: "The Odin Project",
    provider: "The Odin Project",
    url: "https://www.theodinproject.com/",
    description: "A full-stack web development path built around real projects.",
    category: "Web Development",
    type: "course",
    level: "beginner",
    cost: "free",
    skills: ["Web development", "Programming"],
  },
  {
    id: "mdn",
    title: "MDN Web Docs",
    provider: "Mozilla",
    url: "https://developer.mozilla.org/",
    description: "The authoritative reference for HTML, CSS, and JavaScript.",
    category: "Web Development",
    type: "article",
    level: "all",
    cost: "free",
    skills: ["Web development"],
  },
  {
    id: "leetcode",
    title: "LeetCode",
    provider: "LeetCode",
    url: "https://leetcode.com/",
    description: "Practice data structures and algorithms for technical interviews.",
    category: "Programming",
    type: "practice",
    level: "intermediate",
    cost: "freemium",
    skills: ["Programming"],
  },
  {
    id: "codecademy",
    title: "Codecademy",
    provider: "Codecademy",
    url: "https://www.codecademy.com/",
    description: "Interactive, in-browser courses across many programming languages.",
    category: "Programming",
    type: "course",
    level: "beginner",
    cost: "freemium",
    skills: ["Programming", "Web development"],
  },

  // ── Data & AI ────────────────────────────────────────────────────────────
  {
    id: "kaggle-learn",
    title: "Kaggle Learn",
    provider: "Kaggle",
    url: "https://www.kaggle.com/learn",
    description: "Short, practical micro-courses on data science and machine learning.",
    category: "Data & AI",
    type: "course",
    level: "beginner",
    cost: "free",
    skills: ["Data analysis", "Machine learning / AI"],
  },
  {
    id: "google-data-analytics",
    title: "Google Data Analytics Certificate",
    provider: "Google / Coursera",
    url: "https://www.coursera.org/professional-certificates/google-data-analytics",
    description: "Job-ready data analytics program covering spreadsheets, SQL, and visualization.",
    category: "Data & AI",
    type: "course",
    level: "beginner",
    cost: "paid",
    skills: ["Data analysis", "Spreadsheets / Excel"],
  },
  {
    id: "fastai",
    title: "Practical Deep Learning for Coders",
    provider: "fast.ai",
    url: "https://course.fast.ai/",
    description: "A top-down, code-first path into modern deep learning.",
    category: "Data & AI",
    type: "course",
    level: "intermediate",
    cost: "free",
    skills: ["Machine learning / AI", "Programming"],
  },
  {
    id: "sql-mode",
    title: "Mode SQL Tutorial",
    provider: "Mode",
    url: "https://mode.com/sql-tutorial/",
    description: "A hands-on SQL tutorial from basics to advanced analytics.",
    category: "Data & AI",
    type: "article",
    level: "beginner",
    cost: "free",
    skills: ["Databases", "Data analysis"],
  },

  // ── Cloud / DevOps ───────────────────────────────────────────────────────
  {
    id: "aws-skillbuilder",
    title: "AWS Skill Builder",
    provider: "Amazon Web Services",
    url: "https://skillbuilder.aws/",
    description: "Official learning for cloud fundamentals and AWS certifications.",
    category: "Cloud & DevOps",
    type: "course",
    level: "beginner",
    cost: "freemium",
    skills: ["Cloud / DevOps"],
  },
  {
    id: "roadmap-sh",
    title: "roadmap.sh",
    provider: "roadmap.sh",
    url: "https://roadmap.sh/",
    description: "Community-driven role-based roadmaps for developers and beyond.",
    category: "Cloud & DevOps",
    type: "article",
    level: "all",
    cost: "free",
    skills: ["Cloud / DevOps", "Programming", "Web development"],
  },

  // ── Design / UX ──────────────────────────────────────────────────────────
  {
    id: "google-ux",
    title: "Google UX Design Certificate",
    provider: "Google / Coursera",
    url: "https://www.coursera.org/professional-certificates/google-ux-design",
    description: "A job-ready introduction to UX research and design.",
    category: "Design",
    type: "course",
    level: "beginner",
    cost: "paid",
    skills: ["UI / UX design", "Graphic design"],
  },
  {
    id: "refactoring-ui",
    title: "Refactoring UI",
    provider: "Adam Wathan & Steve Schoger",
    url: "https://www.refactoringui.com/",
    description: "Practical visual design tactics for developers and designers.",
    category: "Design",
    type: "book",
    level: "intermediate",
    cost: "paid",
    skills: ["UI / UX design"],
  },
  {
    id: "laws-of-ux",
    title: "Laws of UX",
    provider: "Jon Yablonski",
    url: "https://lawsofux.com/",
    description: "A concise reference of UX principles with examples.",
    category: "Design",
    type: "article",
    level: "all",
    cost: "free",
    skills: ["UI / UX design"],
  },

  // ── Marketing & content ──────────────────────────────────────────────────
  {
    id: "google-digital-garage",
    title: "Fundamentals of Digital Marketing",
    provider: "Google",
    url: "https://learndigital.withgoogle.com/digitalgarage",
    description: "A free certification covering the fundamentals of digital marketing.",
    category: "Marketing",
    type: "course",
    level: "beginner",
    cost: "free",
    skills: ["Digital marketing", "Content writing"],
  },
  {
    id: "hubspot-academy",
    title: "HubSpot Academy",
    provider: "HubSpot",
    url: "https://academy.hubspot.com/",
    description: "Free certifications in inbound marketing, content, and sales.",
    category: "Marketing",
    type: "course",
    level: "beginner",
    cost: "free",
    skills: ["Digital marketing", "Content writing"],
  },

  // ── Business & product ───────────────────────────────────────────────────
  {
    id: "coursera-pm",
    title: "Digital Product Management",
    provider: "University of Virginia / Coursera",
    url: "https://www.coursera.org/specializations/uva-darden-digital-product-management",
    description: "Foundations of modern product management and agile delivery.",
    category: "Business",
    type: "course",
    level: "intermediate",
    cost: "paid",
    skills: ["Project management tools"],
  },
  {
    id: "svpg-inspired",
    title: "Inspired: How to Create Products Customers Love",
    provider: "Marty Cagan",
    url: "https://www.svpg.com/inspired-how-to-create-products-customers-love/",
    description: "A widely-read guide to building products users love.",
    category: "Business",
    type: "book",
    level: "intermediate",
    cost: "paid",
    skills: ["Project management tools"],
  },

  // ── Career & interview prep ──────────────────────────────────────────────
  {
    id: "levels-fyi",
    title: "Levels.fyi",
    provider: "Levels.fyi",
    url: "https://www.levels.fyi/",
    description: "Real compensation data to benchmark roles and negotiate offers.",
    category: "Career",
    type: "tool",
    level: "all",
    cost: "free",
    skills: [],
  },
  {
    id: "techinterviewhandbook",
    title: "Tech Interview Handbook",
    provider: "Yangshun Tay",
    url: "https://www.techinterviewhandbook.org/",
    description: "A curated, free guide to acing technical interviews.",
    category: "Career",
    type: "article",
    level: "intermediate",
    cost: "free",
    skills: ["Programming"],
  },
  {
    id: "khan-academy",
    title: "Khan Academy",
    provider: "Khan Academy",
    url: "https://www.khanacademy.org/",
    description: "Free foundational courses in math, economics, and more.",
    category: "Foundations",
    type: "course",
    level: "beginner",
    cost: "free",
    skills: [],
  },
  {
    id: "coursera-learning-how-to-learn",
    title: "Learning How to Learn",
    provider: "Deep Teaching Solutions / Coursera",
    url: "https://www.coursera.org/learn/learning-how-to-learn",
    description: "Evidence-based techniques to learn anything more effectively.",
    category: "Foundations",
    type: "course",
    level: "all",
    cost: "freemium",
    skills: [],
  },
];

export const LEARNING_CATEGORIES: string[] = Array.from(
  new Set(LEARNING_CATALOG.map((r) => r.category)),
).sort();

export const CATALOG_BY_ID: Record<string, LearningResource> = LEARNING_CATALOG.reduce<
  Record<string, LearningResource>
>((acc, resource) => {
  acc[resource.id] = resource;
  return acc;
}, {});
